// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student_svc.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Student struct {
	StudentId            string   `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	StudentName          string   `protobuf:"bytes,2,opt,name=studentName,proto3" json:"studentName,omitempty"`
	ClassName            string   `protobuf:"bytes,3,opt,name=className,proto3" json:"className,omitempty"`
	Schoolname           string   `protobuf:"bytes,4,opt,name=schoolname,proto3" json:"schoolname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a403c85fe99412f, []int{0}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetStudentId() string {
	if m != nil {
		return m.StudentId
	}
	return ""
}

func (m *Student) GetStudentName() string {
	if m != nil {
		return m.StudentName
	}
	return ""
}

func (m *Student) GetClassName() string {
	if m != nil {
		return m.ClassName
	}
	return ""
}

func (m *Student) GetSchoolname() string {
	if m != nil {
		return m.Schoolname
	}
	return ""
}

type CreateStuReq struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStuReq) Reset()         { *m = CreateStuReq{} }
func (m *CreateStuReq) String() string { return proto.CompactTextString(m) }
func (*CreateStuReq) ProtoMessage()    {}
func (*CreateStuReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a403c85fe99412f, []int{1}
}

func (m *CreateStuReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStuReq.Unmarshal(m, b)
}
func (m *CreateStuReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStuReq.Marshal(b, m, deterministic)
}
func (m *CreateStuReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStuReq.Merge(m, src)
}
func (m *CreateStuReq) XXX_Size() int {
	return xxx_messageInfo_CreateStuReq.Size(m)
}
func (m *CreateStuReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStuReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStuReq proto.InternalMessageInfo

func (m *CreateStuReq) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type CreateStuRes struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStuRes) Reset()         { *m = CreateStuRes{} }
func (m *CreateStuRes) String() string { return proto.CompactTextString(m) }
func (*CreateStuRes) ProtoMessage()    {}
func (*CreateStuRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a403c85fe99412f, []int{2}
}

func (m *CreateStuRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStuRes.Unmarshal(m, b)
}
func (m *CreateStuRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStuRes.Marshal(b, m, deterministic)
}
func (m *CreateStuRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStuRes.Merge(m, src)
}
func (m *CreateStuRes) XXX_Size() int {
	return xxx_messageInfo_CreateStuRes.Size(m)
}
func (m *CreateStuRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStuRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStuRes proto.InternalMessageInfo

func (m *CreateStuRes) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type ReadStuReq struct {
	Schoolname           string   `protobuf:"bytes,1,opt,name=schoolname,proto3" json:"schoolname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadStuReq) Reset()         { *m = ReadStuReq{} }
func (m *ReadStuReq) String() string { return proto.CompactTextString(m) }
func (*ReadStuReq) ProtoMessage()    {}
func (*ReadStuReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a403c85fe99412f, []int{3}
}

func (m *ReadStuReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadStuReq.Unmarshal(m, b)
}
func (m *ReadStuReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadStuReq.Marshal(b, m, deterministic)
}
func (m *ReadStuReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadStuReq.Merge(m, src)
}
func (m *ReadStuReq) XXX_Size() int {
	return xxx_messageInfo_ReadStuReq.Size(m)
}
func (m *ReadStuReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadStuReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadStuReq proto.InternalMessageInfo

func (m *ReadStuReq) GetSchoolname() string {
	if m != nil {
		return m.Schoolname
	}
	return ""
}

type ReadStuRes struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadStuRes) Reset()         { *m = ReadStuRes{} }
func (m *ReadStuRes) String() string { return proto.CompactTextString(m) }
func (*ReadStuRes) ProtoMessage()    {}
func (*ReadStuRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a403c85fe99412f, []int{4}
}

func (m *ReadStuRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadStuRes.Unmarshal(m, b)
}
func (m *ReadStuRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadStuRes.Marshal(b, m, deterministic)
}
func (m *ReadStuRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadStuRes.Merge(m, src)
}
func (m *ReadStuRes) XXX_Size() int {
	return xxx_messageInfo_ReadStuRes.Size(m)
}
func (m *ReadStuRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadStuRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadStuRes proto.InternalMessageInfo

func (m *ReadStuRes) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type ListStuReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStuReq) Reset()         { *m = ListStuReq{} }
func (m *ListStuReq) String() string { return proto.CompactTextString(m) }
func (*ListStuReq) ProtoMessage()    {}
func (*ListStuReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a403c85fe99412f, []int{5}
}

func (m *ListStuReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStuReq.Unmarshal(m, b)
}
func (m *ListStuReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStuReq.Marshal(b, m, deterministic)
}
func (m *ListStuReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStuReq.Merge(m, src)
}
func (m *ListStuReq) XXX_Size() int {
	return xxx_messageInfo_ListStuReq.Size(m)
}
func (m *ListStuReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStuReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListStuReq proto.InternalMessageInfo

type ListStuRes struct {
	Student              []*Student `protobuf:"bytes,1,rep,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListStuRes) Reset()         { *m = ListStuRes{} }
func (m *ListStuRes) String() string { return proto.CompactTextString(m) }
func (*ListStuRes) ProtoMessage()    {}
func (*ListStuRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a403c85fe99412f, []int{6}
}

func (m *ListStuRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStuRes.Unmarshal(m, b)
}
func (m *ListStuRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStuRes.Marshal(b, m, deterministic)
}
func (m *ListStuRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStuRes.Merge(m, src)
}
func (m *ListStuRes) XXX_Size() int {
	return xxx_messageInfo_ListStuRes.Size(m)
}
func (m *ListStuRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStuRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListStuRes proto.InternalMessageInfo

func (m *ListStuRes) GetStudent() []*Student {
	if m != nil {
		return m.Student
	}
	return nil
}

func init() {
	proto.RegisterType((*Student)(nil), "model.Student")
	proto.RegisterType((*CreateStuReq)(nil), "model.CreateStuReq")
	proto.RegisterType((*CreateStuRes)(nil), "model.CreateStuRes")
	proto.RegisterType((*ReadStuReq)(nil), "model.ReadStuReq")
	proto.RegisterType((*ReadStuRes)(nil), "model.ReadStuRes")
	proto.RegisterType((*ListStuReq)(nil), "model.ListStuReq")
	proto.RegisterType((*ListStuRes)(nil), "model.ListStuRes")
}

func init() { proto.RegisterFile("student_svc.proto", fileDescriptor_4a403c85fe99412f) }

var fileDescriptor_4a403c85fe99412f = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x65, 0xad, 0x5a, 0x33, 0x2d, 0x95, 0x8e, 0x97, 0x12, 0x44, 0x4a, 0x4f, 0x3d, 0x48, 0x90,
	0x88, 0x1f, 0x67, 0x3d, 0x09, 0xe2, 0x21, 0xf9, 0x01, 0x12, 0xb3, 0x03, 0x16, 0xd2, 0xac, 0x66,
	0x36, 0x05, 0x7f, 0x81, 0x7f, 0xc8, 0x1f, 0x28, 0xd9, 0x8c, 0x49, 0x6c, 0x44, 0xe8, 0x71, 0xdf,
	0x9b, 0xf7, 0xe6, 0xbd, 0x61, 0x61, 0xca, 0xb6, 0xd4, 0x94, 0xdb, 0x67, 0xde, 0xa4, 0xc1, 0x5b,
	0x61, 0xac, 0xc1, 0x83, 0xb5, 0xd1, 0x94, 0x2d, 0x3e, 0x15, 0x0c, 0xe3, 0x9a, 0xc4, 0x53, 0xf0,
	0x64, 0xee, 0x41, 0xcf, 0xd4, 0x5c, 0x2d, 0xbd, 0xa8, 0x05, 0x70, 0x0e, 0x23, 0x79, 0x3c, 0x25,
	0x6b, 0x9a, 0xed, 0x39, 0xbe, 0x0b, 0x55, 0xfa, 0x34, 0x4b, 0x98, 0x1d, 0x3f, 0xa8, 0xf5, 0x0d,
	0x80, 0x67, 0x00, 0x9c, 0xbe, 0x1a, 0x93, 0xe5, 0x15, 0xbd, 0xef, 0xe8, 0x0e, 0xb2, 0xb8, 0x85,
	0xf1, 0x7d, 0x41, 0x89, 0xa5, 0xd8, 0x96, 0x11, 0xbd, 0xe3, 0x12, 0x86, 0x62, 0xee, 0xb2, 0x8c,
	0xc2, 0x49, 0xe0, 0x22, 0x07, 0x12, 0x37, 0xfa, 0xa1, 0xb7, 0x94, 0xbc, 0x83, 0xf2, 0x1c, 0x20,
	0xa2, 0x44, 0xcb, 0xc6, 0xdf, 0x09, 0x55, 0x2f, 0xe1, 0x75, 0x67, 0x7a, 0x97, 0x2d, 0x63, 0x80,
	0xc7, 0x15, 0xdb, 0x7a, 0x4b, 0xe5, 0xd2, 0xbc, 0xb6, 0x5c, 0x06, 0xff, 0xb8, 0x84, 0x5f, 0x0a,
	0x26, 0xb1, 0xd5, 0x25, 0xe5, 0x36, 0xa6, 0x62, 0xb3, 0x4a, 0x09, 0xaf, 0xc0, 0x6b, 0x8a, 0xe3,
	0x89, 0x08, 0xbb, 0x47, 0xf4, 0xff, 0x00, 0x19, 0x6f, 0xe0, 0x58, 0x7a, 0xdc, 0x7d, 0xc4, 0xae,
	0x1e, 0x4e, 0x65, 0xae, 0xbd, 0x86, 0xdf, 0x83, 0x18, 0x43, 0x38, 0x92, 0xe8, 0xdc, 0x28, 0xda,
	0x66, 0x7e, 0x0f, 0xe2, 0x0b, 0xf5, 0x72, 0xe8, 0xbe, 0xdb, 0xe5, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc1, 0xa2, 0x70, 0x88, 0x83, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StduentServiceClient is the client API for StduentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StduentServiceClient interface {
	CreateStu(ctx context.Context, in *CreateStuReq, opts ...grpc.CallOption) (*CreateStuRes, error)
	ReadStuBySchool(ctx context.Context, in *ReadStuReq, opts ...grpc.CallOption) (*ReadStuRes, error)
	ListStus(ctx context.Context, in *ListStuReq, opts ...grpc.CallOption) (StduentService_ListStusClient, error)
}

type stduentServiceClient struct {
	cc *grpc.ClientConn
}

func NewStduentServiceClient(cc *grpc.ClientConn) StduentServiceClient {
	return &stduentServiceClient{cc}
}

func (c *stduentServiceClient) CreateStu(ctx context.Context, in *CreateStuReq, opts ...grpc.CallOption) (*CreateStuRes, error) {
	out := new(CreateStuRes)
	err := c.cc.Invoke(ctx, "/model.StduentService/CreateStu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stduentServiceClient) ReadStuBySchool(ctx context.Context, in *ReadStuReq, opts ...grpc.CallOption) (*ReadStuRes, error) {
	out := new(ReadStuRes)
	err := c.cc.Invoke(ctx, "/model.StduentService/ReadStuBySchool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stduentServiceClient) ListStus(ctx context.Context, in *ListStuReq, opts ...grpc.CallOption) (StduentService_ListStusClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StduentService_serviceDesc.Streams[0], "/model.StduentService/ListStus", opts...)
	if err != nil {
		return nil, err
	}
	x := &stduentServiceListStusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StduentService_ListStusClient interface {
	Recv() (*ListStuRes, error)
	grpc.ClientStream
}

type stduentServiceListStusClient struct {
	grpc.ClientStream
}

func (x *stduentServiceListStusClient) Recv() (*ListStuRes, error) {
	m := new(ListStuRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StduentServiceServer is the server API for StduentService service.
type StduentServiceServer interface {
	CreateStu(context.Context, *CreateStuReq) (*CreateStuRes, error)
	ReadStuBySchool(context.Context, *ReadStuReq) (*ReadStuRes, error)
	ListStus(*ListStuReq, StduentService_ListStusServer) error
}

// UnimplementedStduentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStduentServiceServer struct {
}

func (*UnimplementedStduentServiceServer) CreateStu(ctx context.Context, req *CreateStuReq) (*CreateStuRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStu not implemented")
}
func (*UnimplementedStduentServiceServer) ReadStuBySchool(ctx context.Context, req *ReadStuReq) (*ReadStuRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadStuBySchool not implemented")
}
func (*UnimplementedStduentServiceServer) ListStus(req *ListStuReq, srv StduentService_ListStusServer) error {
	return status.Errorf(codes.Unimplemented, "method ListStus not implemented")
}

func RegisterStduentServiceServer(s *grpc.Server, srv StduentServiceServer) {
	s.RegisterService(&_StduentService_serviceDesc, srv)
}

func _StduentService_CreateStu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StduentServiceServer).CreateStu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.StduentService/CreateStu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StduentServiceServer).CreateStu(ctx, req.(*CreateStuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StduentService_ReadStuBySchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StduentServiceServer).ReadStuBySchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.StduentService/ReadStuBySchool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StduentServiceServer).ReadStuBySchool(ctx, req.(*ReadStuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StduentService_ListStus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListStuReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StduentServiceServer).ListStus(m, &stduentServiceListStusServer{stream})
}

type StduentService_ListStusServer interface {
	Send(*ListStuRes) error
	grpc.ServerStream
}

type stduentServiceListStusServer struct {
	grpc.ServerStream
}

func (x *stduentServiceListStusServer) Send(m *ListStuRes) error {
	return x.ServerStream.SendMsg(m)
}

var _StduentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.StduentService",
	HandlerType: (*StduentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStu",
			Handler:    _StduentService_CreateStu_Handler,
		},
		{
			MethodName: "ReadStuBySchool",
			Handler:    _StduentService_ReadStuBySchool_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListStus",
			Handler:       _StduentService_ListStus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "student_svc.proto",
}
